"""Add is_active column to jobs table

Revision ID: 0540d7d46c28
Revises: 80228c4e0341
Create Date: 2025-02-22 21:37:17.452127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0540d7d46c28'
down_revision = '80228c4e0341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('interview_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_date', sa.DATE(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
