"""Add cascade delete to job applications

Revision ID: 3429bec56521
Revises: ab3cab8d637b
Create Date: 2025-02-18 15:36:53.541670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3429bec56521'
down_revision = 'ab3cab8d637b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('educational_backgrounds', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)

    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_constraint('job_application_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('job_application_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_application_ibfk_2', 'jobs', ['job_id'], ['id'])
        batch_op.create_foreign_key('job_application_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('educational_backgrounds', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    op.create_table('work_experience',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('responsibilities', mysql.TEXT(), nullable=True),
    sa.Column('achievements', mysql.TEXT(), nullable=True),
    sa.Column('skills_acquired', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='work_experience_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
