"""Replaced application_instruction with grade

Revision ID: 4e9a29322ecf
Revises: b8bf01b2b910
Create Date: 2025-02-06 14:49:26.511167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e9a29322ecf'
down_revision = 'b8bf01b2b910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.drop_column('application_instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_instructions', mysql.TEXT(), nullable=False))
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
