"""update educational background table

Revision ID: 5813432d79c6
Revises: c3b2912b025e
Create Date: 2025-01-28 21:54:14.482675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5813432d79c6'
down_revision = 'c3b2912b025e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educational_background')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_background',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('high_school_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('high_school_year_completed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_school_grade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('high_school_extracurricular', mysql.TEXT(), nullable=True),
    sa.Column('university_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('university_degree_program', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('university_field_of_study', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('university_grade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('university_start_date', sa.DATE(), nullable=True),
    sa.Column('university_end_date', sa.DATE(), nullable=True),
    sa.Column('certificate_paths', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='educational_background_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
