"""Add interview_date column to jobs table

Revision ID: 5adccc40625f
Revises: d6813b3024ae
Create Date: 2025-02-23 09:10:21.508629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adccc40625f'
down_revision = 'd6813b3024ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('interview_date')

    # ### end Alembic commands ###
