"""Remove publications and skills_experience fields from employment_details

Revision ID: 5c4b220cfae2
Revises: 3429bec56521
Create Date: 2025-02-21 18:40:40.126158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c4b220cfae2'
down_revision = '3429bec56521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_details', schema=None) as batch_op:
        batch_op.drop_column('skills_experience')
        batch_op.drop_column('publications')

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('saved_jobs_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('saved_jobs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('saved_jobs_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('saved_jobs_ibfk_2', 'jobs', ['job_id'], ['id'])
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('employment_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publications', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('skills_experience', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
