"""Change year column to String

Revision ID: 6308e7395fe6
Revises: 5c4b220cfae2
Create Date: 2025-02-22 10:20:52.362679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6308e7395fe6'
down_revision = '5c4b220cfae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relevant_courses_and_professional_bodies', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relevant_courses_and_professional_bodies', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
