"""Add new fields to personal_details table

Revision ID: b8bf01b2b910
Revises: 5813432d79c6
Create Date: 2025-01-29 14:22:39.319255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bf01b2b910'
down_revision = '5813432d79c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_contact_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('alternative_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('disability_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('disability_registration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('criminal_conviction', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('criminal_offence_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dismissal_from_employment', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('dismissal_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dismissal_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_details', schema=None) as batch_op:
        batch_op.drop_column('dismissal_date')
        batch_op.drop_column('dismissal_reason')
        batch_op.drop_column('dismissal_from_employment')
        batch_op.drop_column('criminal_offence_details')
        batch_op.drop_column('criminal_conviction')
        batch_op.drop_column('disability_registration')
        batch_op.drop_column('disability_details')
        batch_op.drop_column('disability')
        batch_op.drop_column('alternative_contact_phone')
        batch_op.drop_column('alternative_contact_name')

    # ### end Alembic commands ###
