"""Update personal_details table fields

Revision ID: c3b2912b025e
Revises: 
Create Date: 2025-01-26 15:48:45.630990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3b2912b025e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_names', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('home_county', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('constituency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postal_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_address', sa.String(length=100), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('email_address')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('postal_address')
        batch_op.drop_column('constituency')
        batch_op.drop_column('home_county')
        batch_op.drop_column('id_number')
        batch_op.drop_column('title')
        batch_op.drop_column('full_names')

    # ### end Alembic commands ###
